//
//  ListViewController.swift
//  TheMovieDB
//
//  Created by Burak AKIN on 28.08.2020.
//  Copyright (c) 2020 Burak AKIN. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListDisplayLogic: class
{
    func displayUpcomingMovies(viewModel: List.UpcomingMovies.ViewModel)
    func displayNowPlayingMovies(viewModel: List.NowPlayingMovies.ViewModel)
    func displayMovieDetail(viewModel: List.SelectedMovie.ViewModel)
    func displaySearchMovies(viewModel: List.SearchMovie.ViewModel)
}

class ListViewController: UIViewController, ListDisplayLogic
{
    var interactor: ListBusinessLogic?
    var router: (NSObjectProtocol & ListRoutingLogic & ListDataPassing)?
    
    // MARK: OUTLETS
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var searchTableView: UITableView!
    @IBOutlet weak var searchTableViewHeightConstraint: NSLayoutConstraint!
    
    //MARK: PROPERTY
    var sections = [Section]()
    
    var upComingSections = [Section]()
    var nowPlayingSections = [Section]()
    var searchMovies: [String] = []
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ListInteractor()
        let presenter = ListPresenter()
        let router = ListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        tableView.registerNib(ListMoviesCell.self)
        tableView.registerNib(SliderCell.self)
        configureSearchBar()
        fetch()
    }
    
    func configureSearchBar()
    {
        let searchController = UISearchController(searchResultsController: nil)
        searchController.searchBar.delegate = self
        searchController.obscuresBackgroundDuringPresentation = false
        searchController.searchBar.placeholder = "Search Places"
        self.navigationItem.searchController = searchController
        self.definesPresentationContext = true
    }
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func fetch()
    {
        interactor?.fetchUpcomingMovies(request: List.UpcomingMovies.Request(model: MoviesUpComingRequest()))
        interactor?.fetchNowPlayingMovies(request: List.NowPlayingMovies.Request(model: MoviesNowPlayingRequest()))
    }
    
    func displayUpcomingMovies(viewModel: List.UpcomingMovies.ViewModel)
    {
        upComingSections = viewModel.sections
        tableView.reloadData()
    }
    func displayNowPlayingMovies(viewModel: List.NowPlayingMovies.ViewModel) {
        nowPlayingSections = viewModel.sections
        tableView.reloadData()
    }
    
    func displayMovieDetail(viewModel: List.SelectedMovie.ViewModel) {
        router?.routeToDetail(segue: nil)
    }
    
    func displaySearchMovies(viewModel: List.SearchMovie.ViewModel) {
        searchMovies = viewModel.title
        searchTableView.reloadData()
        searchTableViewHeightConstraint.constant = CGFloat(44 * searchMovies.count)
    }
}


extension ListViewController: UITableViewDelegate, UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        if tableView == searchTableView {
            return 1
        }
        else {
            sections = nowPlayingSections +
                       upComingSections
            return sections.count
        }
        
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if tableView == searchTableView {
            return searchMovies.count
        }
        else {
            return sections[section].items.count
        }
        
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if tableView == searchTableView {
            let cell = UITableViewCell(style: .default, reuseIdentifier: "Cell")
            cell.textLabel?.text = searchMovies[indexPath.row]
            return cell
        }
        else {
            let item = sections[indexPath.section].items[indexPath.row]
            let cell = tableView.dequeueCell(item, for: indexPath)
            item.configure(cell: cell)
            
            switch cell {
            case let cell as SliderCell:
                cell.delegate = self
            default:
                break
            }
            
            return cell
        }
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        if tableView == searchTableView {
            return UITableView.automaticDimension
        }
        else {
            switch sections[indexPath.section].items[0] {
            case is SliderCellConfigurator:
                return 300
            default:
                return UITableView.automaticDimension
            }
        }
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if tableView == searchTableView {
            interactor?.goToDetail(request: List.SelectedMovie.Request(type: .Search, index: indexPath.row))
        }
        else {
            interactor?.goToDetail(request: List.SelectedMovie.Request(type: .Upcoming, index: indexPath.row))
        }
        
    }
    
}

extension ListViewController: CollectionViewDelegate {
    func setIndex(index: Int) {
        interactor?.goToDetail(request: List.SelectedMovie.Request(type: .NowPlaying, index: index))
    }
    
    
}


extension ListViewController: UISearchBarDelegate {

    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        if searchText.count > 2 {
            let request = List.SearchMovie.Request(model: SearchMovieRequest(query: searchText))
            interactor?.fetchSearchMovies(request: request)
        }
        else if searchText.count == 0 {
            searchTableViewHeightConstraint.constant = 0
            searchMovies.removeAll()
            searchTableView.reloadData()
        }
    }
    
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        let request = List.SearchMovie.Request(model: SearchMovieRequest(query: searchBar.text ?? ""))
        interactor?.fetchSearchMovies(request: request)
    }
    
    func searchBarCancelButtonClicked(_ searchBar: UISearchBar) {
        searchTableViewHeightConstraint.constant = 0
        searchMovies.removeAll()
        searchTableView.reloadData()
    }
    
}
