//
//  ListModels.swift
//  TheMovieDB
//
//  Created by Burak AKIN on 28.08.2020.
//  Copyright (c) 2020 Burak AKIN. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum List
{
    // MARK: Use cases
    
    enum UpcomingMovies
    {
        struct Request
        {
            let model: MoviesUpComingRequest
        }
        struct Response
        {
            let response: [MovieList]
        }
        struct ViewModel
        {
            let sections: [Section]
        }
    }
    
    enum NowPlayingMovies
    {
        struct Request
        {
            let model: MoviesNowPlayingRequest
        }
        struct Response
        {
            let response: [MovieList]
        }
        struct ViewModel
        {
            let sections: [Section]
        }
    }
    
    enum SelectedMovie
    {
        struct Request
        {
            let type: MoviesType
            let index: Int
            
            enum MoviesType {
                case Upcoming
                case NowPlaying
                case Search
            }
        }
        struct Response
        {
            
        }
        struct ViewModel
        {
            
        }
    }
    
    enum SearchMovie
    {
        struct Request
        {
            let model: SearchMovieRequest
        }
        struct Response
        {
            let movies: [MovieList]
        }
        struct ViewModel
        {
            let title: [String]
        }
    }
}
