//
//  ListWorker.swift
//  TheMovieDB
//
//  Created by Burak AKIN on 28.08.2020.
//  Copyright (c) 2020 Burak AKIN. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListWorker
{
    func fetchUpcomingMovies(request: MoviesUpComingRequest, completion: @escaping DecodableResultWithBaseHandler<[MovieList]>)
    {
        MovieRouter.moviesUpcoming(request).executeDecodable(withBase: completion)
    }
    
    func fetchNowPlayingMovies(request: MoviesNowPlayingRequest, completion: @escaping DecodableResultWithBaseHandler<[MovieList]>)
    {
        MovieRouter.moviesNowPlaying(request).executeDecodable(withBase: completion)
    }
}
