//
//  MovieDetailRouter.swift
//  TheMovieDB
//
//  Created by Burak AKIN on 28.08.2020.
//  Copyright (c) 2020 Burak AKIN. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MovieDetailRoutingLogic
{
  func routeToDetail(segue: UIStoryboardSegue?)
}

protocol MovieDetailDataPassing
{
  var dataStore: MovieDetailDataStore? { get }
}

class MovieDetailRouter: NSObject, MovieDetailRoutingLogic, MovieDetailDataPassing
{
  weak var viewController: MovieDetailViewController?
  var dataStore: MovieDetailDataStore?
  
  // MARK: Routing
  
  func routeToDetail(segue: UIStoryboardSegue?)
  {
      let destinationVC = MovieDetailViewController()
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: MovieDetailViewController, destination: MovieDetailViewController)
  {
    source.navigationController?.pushViewController(destination, animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: MovieDetailDataStore, destination: inout MovieDetailDataStore)
  {
    destination.selectedMovieId = source.selectedMovieId
  }
}
