//
//  MovieDetailViewController.swift
//  TheMovieDB
//
//  Created by Burak AKIN on 28.08.2020.
//  Copyright (c) 2020 Burak AKIN. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailDisplayLogic: class
{
    func displayDetail(viewModel: MovieDetailm.Detail.ViewModel)
    func goToDetail(viewModel: MovieDetailm.SelectedMovie.ViewModel)
}

class MovieDetailViewController: UIViewController, MovieDetailDisplayLogic
{
    var interactor: MovieDetailBusinessLogic?
    var router: (NSObjectProtocol & MovieDetailRoutingLogic & MovieDetailDataPassing)?
    
    @IBOutlet weak var tableView: UITableView!
  
    
    var sections: [Section] = []
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = MovieDetailInteractor()
        let presenter = MovieDetailPresenter()
        let router = MovieDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        tableView.delegate = self
        tableView.dataSource = self
        tableView.registerNib(MovieDetailCell.self)
        tableView.registerNib(SimilarMoviesCell.self)
        
        fetchMovieDetail()
        
    
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func fetchMovieDetail()
    {
        interactor?.fetchMovieDetail(request: MovieDetailm.Detail.Request())
    }
    
    func displayDetail(viewModel: MovieDetailm.Detail.ViewModel) {
        sections = viewModel.sections
        tableView.reloadData()
    }
    
    func goToDetail(viewModel: MovieDetailm.SelectedMovie.ViewModel) {
        router?.routeToDetail(segue: nil)
    }
}


extension MovieDetailViewController: UITableViewDelegate, UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return sections.count
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return sections[section].items.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let item = sections[indexPath.section].items[indexPath.row]
        let cell = tableView.dequeueCell(item, for: indexPath)
        item.configure(cell: cell)
        
        switch cell {
        case let cell as SimilarMoviesCell:
            cell.delegate = self
        default:
            break
        }
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        switch sections[indexPath.section].items[0] {
        case is SimilarMoviesCellConfigurator:
            return 350
        default:
            return UITableView.automaticDimension
        }
    }
    
}

extension MovieDetailViewController: SimilarMoviesCollectionViewDelegate {
    func setIndex(index: Int) {
        interactor?.goToDetail(request: MovieDetailm.SelectedMovie.Request(index: index))
    }
    
    
}
