//
//  MovieDetailWorker.swift
//  TheMovieDB
//
//  Created by Burak AKIN on 28.08.2020.
//  Copyright (c) 2020 Burak AKIN. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MovieDetailWorker
{
    func fetchMovieDetails(request: MovieDetailRequest, completion: @escaping DecodableResultWithoutBaseHandler<MovieDetail>)
    {
        MovieRouter.movieDetail(request).executeDecodable(withoutBase: completion)
    }
    
    func fetchSimilarMovies(request: MovieDetailRequest, completion: @escaping DecodableResultWithBaseHandler<[MovieList]>)
    {
        MovieRouter.movieDetailSimilar(request).executeDecodable(withBase: completion)
    }
    
}
